PROGRAM MAIN
  INTEGER :: ARRAY(5)
  LOGICAL :: MASK(5)
  character(LEN=5) :: TESTSTRING
  
  ARRAY = (/6,2,50,-4,1/)
  MASK = .FALSE.
  MASK(1) = .TRUE.
  MASK(5) = .TRUE.

  print*, PACK(ARRAY,MASK)

  TESTSTRING = 'A B 1'

  PRINT*, TESTSTRING(4:4).EQ.'B'

  TESTSTRING(3:3) = 'F'

  PRINT*, TESTSTRING

  PRINT*, LEN(TESTSTRING)
  
END PROGRAM MAIN
